"""Named constants for User domain rules."""

MIN_DISPLAY_NAME_LENGTH: int = 1
MAX_DISPLAY_NAME_LENGTH: int = 50
MAX_USER_ID_LENGTH: int = 64
MAX_EMAIL_LENGTH: int = 254

ERROR_USER_INVALID_ID: str = "USER_INVALID_ID"
ERROR_USER_INVALID_DISPLAY_NAME: str = "USER_INVALID_DISPLAY_NAME"
ERROR_USER_INVALID_EMAIL: str = "USER_INVALID_EMAIL"
